# -*- coding: utf-8 -*-
import json, re, html

# 读取已提取的 (英文术语, 英文释义)
terms = json.load(open('_glossary_raw.json', encoding='utf-8'))

# 中文译名字典（按英文术语精确匹配；页面本身已含中文的术语已尽量采用原译）
zh = {
 # ---- A ----
 "Abaft":"船尾之后（在…之后，靠近船尾方向）",
 "Abaft the beam":"正横后（与船首夹角大于90度）",
 "Abandon":"弃货（放弃全部或部分货物）",
 "Abatement":"减让（对损坏或溢收的折扣）",
 "Abeam":"正横（与龙骨中线成直角的方向）",
 "Able Bodied Seamen (A.B.)":"一级水兵（熟练水手，缩写A.B.）",
 "Able Seaman (A.B.)":"熟练水手（甲板部无执照船员，缩写A.B.）",
 "Aboard":"在船上／装船",
 "Above board":"甲板之上（公开透明，无可隐瞒）",
 "Above-water hull":"水线以上船体",
 "Absentee pennant":"缺勤旗（表示指挥官不在舰上）",
 "Absolute bearing":"绝对方位（相对正北的方位）",
 "Absorption":"吸收（承运人对特殊费用的自担）",
 "Acceptance":"承兑／接受",
 "Acceptance of Goods":"收货（承运人对货物的接受与责任起始）",
 "Accessorial (AC)":"附加服务",
 "Accessorial Charges":"附加费",
 "Accommodation ladder":"舷梯",
 "Account Party/Accountee":"开证申请人／付款方（进口商/买方）",
 "Acknowledgement of Receipt":"收货确认",
 "Acquiescence":"默认（未异议即视为同意提单条款）",
 "Act of God":"不可抗力（天灾，如洪水、雷击、飓风）",
 "Act of Man":"共同海损性质的自愿牺牲（非天灾的人为行为）",
 "Act of Pardon/Act of Grace":"特许状（准许私掠船行动的信函）",
 "Activity Based Costing (ABS)":"作业成本法（ABC，按活动核算成本）",
 "Activity Based Costing (ABC)":"作业成本法",
 "Ad Hoc Charter":"临时包船（一次性租船）",
 "Ad Valorem":"从价（按价值计，如从价税）",
 "Add-Ons":"附加费（海运费之外的附加）",
 "Admiral":"海军上将",
 "Admiralty":"海军部（海军主管机关）",
 "Admiralty Court":"海事法庭",
 "Admiralty Law":"海商法（海事法）",
 "Adrift":"漂浮失控（未系泊、随风流漂移）",
 "Advance":"提前转运（改配更早开航的船）",
 "Advance Against Documents":"凭单预付款",
 "Advance Note":"预支单（发给船员一个月工资）",
 "Advance Shipment Notification (ASN)":"发货预先通知（ASN）",
 "Advanced Charge":"预付费用（代理垫付后向收货人收回）",
 "Adventure":"冒险装运（货主自负风险的装运）",
 "Advice":"通知（发货通知）",
 "Advice of Shipment":"发货通知（告知买方已装运）",
 "Advising Bank":"通知行",
 "Advisory Capacity":"顾问身份（无权擅自决定）",
 "Affiliate":"关联公司",
 "Affreightment, Contract of":"运输合同（租船/订舱合同）",
 "Afloat":"漂浮（在航、未搁浅）",
 "Aft":"船尾方向",
 "Afternoon watch":"下午班（12:00–16:00）",
 "Against All Risks (AAR)":"一切险（AAR）",
 "Agency Agreement":"代理协议",
 "Agency Fee":"代理费",
 "Agency for International Development (AID)":"国际开发署（美国USAID）",
 "Agency tariff":"代理运价本",
 "Agent":"代理人",
 "Aggregate Shipment":"集中托运（多票合并为一票）",
 "Aggregated Shipments":"集中托运（合并运输）",
 "Agreed Valuation":"约定价值",
 "Agreed Weight":"约定重量",
 "Agriculture Quarantine Inspection (AQI)":"农业检疫（美国AQI）",
 "Aground":"搁浅（船底触底）",
 "Ahead":"船首前方",
 "Ahoy":"嗬（船上呼唤用语）",
 "Ahull":"船身横浪（无帆任浪）",
 "Aid to Navigation (ATON)":"助航设施",
 "Air Freight Forwarder":"航空货运代理",
 "Air Waybill (AWB)":"空运提单（AWB）",
 "All Hands":"全体船员",
 "All In":"全包价（起讫地总费，含一切）",
 "All Inclusive (AI)":"全包（费率含所有费用，无附加）",
 "All night in":"整夜在港（无夜班）",
 "All Risk":"一切险（保险）",
 "All Water":"全水运（仅水路运输）",
 "Allision":"碰撞（移动船撞固定物）",
 "Allotment":"分配舱位（指定给某方的运力份额）",
 "All-Risk Clause":"一切险条款",
 "All-Risk Insurance":"一切险保险",
 "Aloft":"桅顶之上（高处）",
 "Alongside":"靠泊（船边交货）",
 "Alternative Rates":"选择费率（取最低费率）",
 "Always Afloat (AA)":"始终漂浮（AA，合同要求船不坐底）",
 "Ambient Temperature":"环境温度",
 "Amendment":"修改（如信用证修改）",
 "American Bureau of Shipping (ABS)":"美国船级社（ABS）",
 "American National Standards Institute (ANSI)":"美国国家标准学会（ANSI）",
 "American Terms (AT)":"美国条款（海运保险术语）",
 "Amidships":"船中部",
 "Anchor":"锚",
 "Anchor ball":"锚球（表示在锚泊的黑色圆球）",
 "Anchor buoy":"锚标（指示锚位的小浮标）",
 "Anchor Chain or Anchor Cable":"锚链",
 "Anchor Detail":"锚泊班（抛起锚作业班组）",
 "Anchor Light":"锚灯（锚泊白灯）",
 "Anchor Rode":"锚缆（连接锚与船的缆）",
 "Anchor Watch":"锚更（值班看锚是否走锚）",
 "Anchorage":"锚地",
 "Anchor's Aweigh":"锚离底",
 "Andrew":"安德鲁（英国皇家海军俚称）",
 "Anglian Container Services (ACS)":"安格利亚集装箱服务（MSC英国）",
 "ANSI X-12":"ANSI X-12（美国EDI标准）",
 "Anti-Submarine Detection Investigation Committee (ASDIC)":"反潜探测委员会（ASDIC，声呐前身）",
 "Anti-submarine warfare (ASW)":"反潜战（ASW）",
 "Any Quantity (AQ)":"任意数量（AQ，不计重量的费率）",
 "Any Time":"任意时间（租船作业时间）",
 "Any-Quantity (AQ)":"任意数量（AQ）",
 "Apparent Good Order":"表面状况良好",
 "Apparent Wind":"视风（真风与船行风合成）",
 "Application Programming Interface (API)":"应用程序接口（API）",
 "Appraisement":"估价（海关核定完税价格）",
 "Arbitrary":" arbitraries（附加费/协定分摊额）",
 "Arbitration":"仲裁",
 "Arbitration Clause":"仲裁条款",
 "Arc of Visibility":"光弧（助航灯可见水平范围）",
 "Armament":"舰载武器",
 "Arrest":"扣押（对船舶的扣押）",
 "Arrival Date":"到达日期",
 "Arrival Notice":"到货通知",
 "Articles of War":"战争条例（海陆军法规）",
 "Artificial Tween Decks (ATD)":"人造二层甲板（ATD）",
 "Ashore":"上岸／搁滩",
 "Asset-Based, Third Party Provider":"资产型第三方物流商",
 "Assignment (AS)":"转让（权益让与）",
 "Assignment of Proceeds":"收益让渡（信用证下收益转让）",
 "Astern":"向船尾／在后",
 "Asylum Harbour":"避风港",
 "ATA Carnet":"ATA单证册（临时进口免税通关单证）",
 "Athwart, athwartships":"横向（与船长方向垂直）",
 "Atlantic Container Line (ACL)":"大西洋集装箱航运（ACL）",
 "Authorized Economic Operator (AEO)":"经认证经营者（AEO，海关AEO）",
 "Automated Broker Interface (ABI)":"自动经纪商接口（ABI，美国海关）",
 "Automated Commercial Environment system (ACE)":"自动化商业环境系统（ACE，美国海关）",
 "Automated Commercial System (ACS)":"自动化商业系统（ACS，美国海关）",
 "Automated Manifest System (AMS)":"自动舱单系统（AMS，美国海关）",
 "Automated System for Customs Data (ASYCUDA)":"海关数据自动化系统（ASYCUDA，联合国）",
 "Automatic Identification System (AIS)":"自动识别系统（AIS，船舶）",
 "Autoridad del Canal de Panama (ACP)":"巴拿马运河管理局（ACP）",
 "Avast - Stop!":"停！（命令停止动作）",
 "Average":"海损（海上损失）",
 "Average Adjusters":"海损理算人",
 "Average Inventory":"平均库存",
 "Average Order Value (AOV)":"平均订单金额（AOV）",
 "Average Selling Price (ASP)":"平均售价（ASP）",
 "Avoirdupois Pound":"常衡磅（≈0.4536公斤）",
 "Awash":"浪拍甲板（船身极低，水常冲洗）",
 "Aweigh":"锚离底（锚刚离海底）",
 "Aye, aye":"是，是（遵命）",
 "Azimuth Circle":"方位圈（测天体方位）",
 "Azimuth Compass":"方位罗经",
 # ---- B ----
 "Back":"后退／后方",
 "Back freight":"退货运费（错运退运费用）",
 "Back haul":"回程运输",
 "Back order":"延期交货（未交订单）",
 "Backhaul":"回程货",
 "Backloader":"后端装载机",
 "Baggage":"行李",
 "Bale":"包（打包货物）",
 "Bale capacity":"包件容积（舱内装包件容积）",
 "Ballast":"压载（压载水/压载物）",
 "Ballast passage":"压载航行（空船/压载航行）",
 "Banks":"浅滩（河/海浅滩）",
 "Barge":"驳船",
 "Base cargo":"基础货（底货）",
 "Base rate":"基本费率",
 "Basket":"篮（组合/批次）",
 "Basis":"基准（计价基础）",
 "Batch":"批次",
 "Battens":"舱壁护条（防货移动）",
 "Beam":"船宽／横梁",
 "Bear away":"转向下风",
 "Bear down":"逼近（向下风靠近）",
 "Bearer":"持票人（不记名）",
 "Before the mast":"在桅前（普通水手）",
 "Beginner":"初学者（新船员）",
 "Beneficiary":"受益人（信用证受益人）",
 "Bermuda":"百慕大（航线/地区）",
 "Berth":"泊位／舱位",
 "Berth cargo":"泊位货（订舱货物）",
 "Berth term":"泊位条款（船边交货条款）",
 "Bespoke":"定制",
 "Bicycle":"自行车（多式联运段）",
 "Bill of Entry":"报关单",
 "Bill of Health":"健康证书（船舶检疫）",
 "Bill of Lading":"提单（B/L）",
 "Bill of Lading Clause":"提单条款",
 "Bill of Sale":"卖据（船舶买卖合同）",
 "Bills of Lading":"提单（复数）",
 "Bitt":"系缆桩",
 "Black list":"黑名单",
 "Blanket rate":"统率（综合费率）",
 "Block stowage":"整块堆装",
 "Boat":"小艇",
 "Boiler":"锅炉",
 "Bolster":"垫木（拖车/平板垫）",
 "Bond":"保税／保函",
 "Bonded":"保税的",
 "Bonded warehouse":"保税仓库",
 "Book":"订舱",
 "Booking":"订舱",
 "Booking note":"订舱单",
 "Booking number":"订舱号",
 "Boom":"吊杆",
 "Boomilever":"悬臂吊",
 "Boot top":"水尺线（船体吃水标志带）",
 "Both to blame":"双方有责（碰撞互有责任）",
 "Bottomry":"船舶抵押（以船抵押借款）",
 "Bow":"船首",
 "Bower":"主锚",
 "Box":"箱（集装箱）",
 "Box car":"棚车（铁路）",
 "Brail":"收帆索",
 "Breakbulk":"散杂货（件杂货）",
 "Breakbulk cargo":"件杂货",
 "Breakbulk vessel":"件杂货船",
 "Breakage":"破碎",
 "Breach":"违反（违约）",
 "Breast line":"横缆（系泊横缆）",
 "Bridge":"驾驶台／桥",
 "Broker":"经纪人",
 "Bulk":"散装",
 "Bulk cargo":"散货",
 "Bulk carrier":"散货船",
 "Bulk freight":"散装货",
 "Bulwark":"舷墙",
 "Bunker":"燃油（船用燃料）",
 "Bunker adjustment factor (BAF)":"燃油附加费（BAF）",
 "Bunker clause":"燃油条款",
 "Buoy":"浮标",
 "Bunker surcharge":"燃油附加费",
 "Buyer":"买方",
 "Bunker Contingency":"燃油应急费",
 "Bin":"箱/仓（仓储）",
 "Bending":"弯板（船体）",
 "Bittacle":"罗经柜",
 "Boom rest":"吊杆托架",
 "Bracket":"托架/括号",
 "Branch":"分支（分支机构）",
 "Brand":"品牌",
 "Break":"中断/破损",
 "Bribe":"贿赂（违规）",
 "Brief":"简要",
 "Brokerage":"经纪费",
 "Build":"建造",
 "Built":"建造（船龄）",
 "Bulge":"鼓出（船体变形）",
 "Bunk":"铺位",
 "Buoyage":"浮标系统",
 "Bureaucracy":"官僚程序",
 "Burn":"燃烧",
 "Burse":"交易所（古语）",
 "Burthen":"载重量（旧称）",
 "Bushel":"蒲式耳（容量单位）",
 "Butt":"对接（板材对接）",
 "Bylaw":"章程（附则）",
 "Bank":"银行（金融）",
 "Bank guarantee":"银行保函",
 "Barratry":"船长/船员恶行（船员欺诈/非法行为）",
 "Barrel":"桶（液体货单位）",
 "Base cargo":"基础货",
 "Batch":"批次",
 "Beacon":"立标（助航）",
 "Bearing":"方位",
 "Belay":"挽牢（绳索固定）",
 "Bell":"钟（船钟）",
 "Bend":"弯曲",
 "Bent":"弯的",
 "Best":"最佳",
 "Between decks":"甲板间",
 "Beware":"当心",
 "Bilateral":"双边",
 "Bill":"账单/票据",
 "Bind":"约束",
 "Binnacle":"罗经柜",
 "Bitt":"系缆桩",
 "Blank":"空白",
 "Blind":"盲的",
 "Block":"块/滑轮",
 "Board":"登船/委员会",
 "Boat":"艇",
 "Body":"主体",
 "Bogie":"转向架（吊具）",
 "Boil":"沸腾",
 "Bolt":"螺栓",
 "Bonded":"保税",
 "Bonus":"奖金",
 "Book":"订舱",
 "Boom":"吊杆",
 "Boot":"靴",
 "Bore":"孔",
 "Boss":"船尾轴毂",
 "Both":"双方",
 "Bottle":"瓶",
 "Bottom":"船底",
 "Bound":"驶往",
 "Bowline":"单套结（绳结）",
 "Box":"箱",
 "Brace":"拉索",
 "Bracket":"托架",
 "Brake":"刹车",
 "Branch":"分支",
 "Brand":"品牌",
 "Brass":"黄铜",
 "Breadth":"宽度",
 "Break":"破损",
 "Breeze":"微风",
 "Brew":"酿造",
 "Bribe":"贿赂",
 "Bridge":"驾驶台",
 "Bright":"明亮的",
 "Bring":"带来",
 "Broad":"宽",
 "Broker":"经纪人",
 "Broken":"破损的",
 "Bronze":"青铜",
 "Brook":"小溪",
 "Broth":"汤",
 "Brown":"棕色",
 "Brush":"刷",
 "Bubble":"气泡",
 "Buck":"美金（口语）",
 "Bucket":"桶",
 "Budge":"移动",
 "Buffer":"缓冲",
 "Build":"建造",
 "Bulge":"鼓出",
 "Bulk":"散装",
 "Bull":"公牛（拉环）",
 "Bullet":"子弹",
 "Bump":"碰撞",
 "Buoy":"浮标",
 "Bureaucracy":"官僚",
 "Burger":"汉堡（口语，非航运）",
 "Burn":"燃烧",
 "Burr":"毛刺",
 "Burst":"爆裂",
 "Bush":"衬套",
 "Bust":"破产",
 "Butt":"对接",
 "Buyer":"买方",
 # ---- C ----
 "Cabin":"舱室",
 "Cable":"电缆/锚链",
 "Cablegram":"海底电报",
 "Cabotage":"沿海运输（内贸航运权）",
 "Caddy":"小箱",
 "Caisson":"沉箱（船闸/坞门）",
 "Calculate":"计算",
 "Calendar":"日历",
 "Call":"挂靠（船挂靠港口）",
 "Call sign":"呼号",
 "Camber":"舯拱（甲板弧度）",
 "Canal":"运河",
 "Cannel":"烛煤（非航运）",
 "Canoe":"独木舟",
 "Cant":"斜置",
 "Capacity":"运力/容积",
 "Capital":"资本",
 "Captain":"船长",
 "Captive":"专用（专用资产）",
 "Car carrier":"汽车滚装船",
 "Car float":"铁路渡驳",
 "Cargo":"货物",
 "Cargo insurance":"货物保险",
 "Cargo liner":"定期货船",
 "Cargo manifest":"载货清单（舱单）",
 "Cargo worthwhile":"有价值货物",
 "Carpenter":"木工（船舶木匠）",
 "Carrier":"承运人",
 "Cartage":"卡车短驳",
 "Cash":"现金",
 "Cash against documents":"凭单付款",
 "Cash in advance":"预付现金",
 "Cash on delivery (COD)":"货到付款（COD）",
 "Cassette":"箱（集装笼）",
 "Casting":"抛（抛锚/抛缆）",
 "Casualty":"意外损失（海难/伤亡）",
 "Catch":"捕获",
 "Category":"类别",
 "Caulking":"填缝（捻缝）",
 "Cause":"原因",
 "Caution":"注意",
 "Caveat":"警告",
 "Ceiling":"舱顶/上限",
 "Cell":"箱格（集装箱格槽）",
 "Cellular":"箱格化的（集装箱船）",
 "Cement":"水泥",
 "Census":"普查",
 "Center":"中心",
 "Central":"中央的",
 "Centre":"中心（英式）",
 "Certificate":"证书",
 "Certificate of origin":"原产地证书",
 "Chain":"链",
 "Chamber":"舱/室",
 "Chandlery":"船用杂货（物料）",
 "Channel":"航道/频道",
 "Charge":"费用",
 "Charterer":"租船人",
 "Charterer's agent":"租船人代理",
 "Charter":"租船/租约",
 "Charter party":"租船合同",
 "Chattel":"动产",
 "Check":"检查/支票",
 "Chief":"首席（如船长/轮机长）",
 "Chill":"冷藏（微冷）",
 "Chock":"垫木/导缆器",
 "CIF":"成本加保险费加运费（CIF）",
 "Cipher":"密码",
 "Circle":"圆",
 "Claim":"索赔",
 "Clamp":"夹具",
 "Clause":"条款",
 "Clean":"清洁的",
 "Clean bill of lading":"清洁提单",
 "Clear":"清关/放空",
 "Clearance":"结关（清关）",
 "Cleat":"系缆耳（羊角桩）",
 "Clerk":"办事员",
 "Climate":"气候",
 "Climb":"爬升",
 "Clip":"夹",
 "Close":"关闭/收盘",
 "Closure":"关闭",
 "Club":"船东保赔协会（P&I Club）",
 "Cluster":"簇（群）",
 "Coast":"海岸",
 "Coaster":"沿海船",
 "Cockpit":"驾驶舱",
 "Code":"代码",
 "Coefficient":"系数",
 "Coffee":"咖啡（非航运）",
 "Coil":"卷（钢材卷）",
 "Cold":"冷",
 "Collapse":"坍塌",
 "Collapsible":"可折叠",
 "Collar":"领圈（轴领）",
 "Collision":"碰撞",
 "Colours":"旗帜（船旗）",
 "Column":"柱/栏",
 "Combination":"联合（联运）",
 "Combustible":"可燃的",
 "Comfort":"舒适",
 "Command":"指挥",
 "Commerce":"商业",
 "Commercial":"商业的",
 "Commission":"佣金",
 "Committee":"委员会",
 "Commodity":"商品",
 "Common carrier":"公共承运人",
 "Company":"公司",
 "Compass":"罗经",
 "Compensation":"赔偿",
 "Competition":"竞争",
 "Complaint":"投诉",
 "Completion":"完成",
 "Composite":"复合（材料）",
 "Compound":"复合",
 "Compulsory":"强制的",
 "Concealment":"隐瞒",
 "Concession":"特许/让步",
 "Consequence":"后果",
 "Console":"控制台",
 "Consignee":"收货人",
 "Consignment":"托运货物",
 "Consignor":"托运人",
 "Consolidation":"拼箱/集运",
 "Console":"控制台",
 "Constellation":"星座（非航运）",
 "Construct":"建造",
 "Consult":"咨询",
 "Consumer":"消费者",
 "Container":"集装箱",
 "Container freight station (CFS)":"集装箱货运站（CFS）",
 "Container yard (CY)":"集装箱堆场（CY）",
 "Containership":"集装箱船",
 "Contents":"内容",
 "Contest":"争议",
 "Continent":"大陆",
 "Continuation":"续（续页）",
 "Contract":"合同",
 "Contribution":"分摊（共同海损分摊）",
 "Control":"控制",
 "Convention":"公约",
 "Conversion":"换算/改装",
 "Conveyor":"输送机",
 "Convoy":"护航队",
 "Cool":"冷却",
 "Cooper":"桶匠（非航运）",
 "Copy":"副本",
 "Copyright":"版权",
 "Cord":"绳（非航运）",
 "Corner":"角",
 "Corporation":"公司",
 "Correction":"更正",
 "Corrode":"腐蚀",
 "Cost":"成本",
 "Coterminous":"同界的",
 "Council":"理事会",
 "Counter":"计数器",
 "Country":"国家",
 "Coupon":"息票/配券",
 "Course":"航向",
 "Covenant":"契约",
 "Cover":"承保/封面",
 "Covered":"有盖的",
 "Cradle":"托架（船台支架）",
 "Craft":"小艇/工艺",
 "Crane":"起重机",
 "Crate":"板条箱",
 "Crew":"船员",
 "Crime":"犯罪",
 "Crisis":"危机",
 "Criteria":"标准",
 "Critical":"关键的",
 "Crop":"作物",
 "Cross":"横交",
 "Crow's nest":"桅顶瞭望台",
 "Cruise":"巡航",
 "Cruiser":"巡洋舰",
 "Crush":"压坏",
 "Cryo":"低温（冷藏）",
 "Cubic":"立方",
 "Cumulative":"累计的",
 "Curb":"路缘（非航运）",
 "Current":"海流/电流",
 "Cursor":"光标（非航运）",
 "Custom":"习惯",
 "Customary":"惯例的",
 "Customer":"客户",
 "Customhouse":"海关",
 "Customs":"海关",
 "Cut":"切割",
 "Cycle":"循环",
 "Cylinder":"气缸/圆柱体",
 # ---- D ----
 "Dangerous goods":"危险货物",
 "Davit":"吊柱（救生艇架）",
 "Dawn":"黎明",
 "Day":"日",
 "Daylight":"日光",
 "Deadeye":"三眼木（索具）",
 "Deadfreight":"空舱费（亏舱费）",
 "Deadweight":"载重吨（DWT）",
 "Deal":"交易",
 "Debenture":"海关退税凭单",
 "Debit":"借记",
 "Debt":"债务",
 "Deck":"甲板",
 "Deck cargo":"甲板货",
 "Declaration":"申报",
 "Decline":"下降",
 "Decree":"法令",
 "Deductible":"免赔额",
 "Deep":"深",
 "Default":"违约/默认",
 "Defect":"缺陷",
 "Defense":"防御",
 "Deficit":"赤字",
 "Delay":"延误",
 "Delegate":"代表",
 "Delivery":"交付",
 "Delivery order":"提货单（D/O）",
 "Demand":"需求",
 "Demurrage":"滞期费",
 "Density":"密度",
 "Depart":"离港",
 "Department":"部门",
 "Dependency":"附属",
 "Deposit":"押金",
 "Depot":"站场/仓库",
 "Depression":"低压（气象）",
 "Depth":"深度",
 "Derrick":"吊杆（重吊）",
 "Description":"描述",
 "Despatch":"速遣（速遣费）",
 "Destination":"目的地",
 "Destuff":"卸箱（掏箱）",
 "Detain":"扣留",
 "Detention":"滞箱费/扣留",
 "Detention charge":"滞箱费",
 "Deviation":"绕航",
 "Device":"装置",
 "Deduction":"扣减",
 "Default":"违约",
 "Definite":"确定的",
 "Degree":"度数",
 "Delay":"延误",
 "Delete":"删除",
 "Deliver":"交付",
 "Demand":"需求",
 "Demise":"转让（光船租赁）",
 "Demurrage":"滞期费",
 "Density":"密度",
 "Deposit":"押金",
 "Depot":"站场",
 "Depth":"深度",
 "Despatch":"速遣",
 "Destination":"目的地",
 "Detention":"滞箱费",
 "Deviation":"绕航",
 "Dial":"刻度盘",
 "Diamond":"菱形",
 "Dictionary":"词典",
 "Difference":"差额",
 "Digest":"摘要",
 "Digital":"数字",
 "Dimension":"尺码",
 "Direct":"直航/直接",
 "Disbursement":"港口使费（代理垫付款）",
 "Discharge":"卸货",
 "Disclosure":"披露",
 "Discount":"折扣",
 "Discover":"发现",
 "Discrimination":"歧视",
 "Disease":"疾病",
 "Displacement":"排水量",
 "Dispute":"争议",
 "Distance":"距离",
 "Distribute":"分销",
 "District":"区域",
 "Diversion":"改港",
 "Divide":"划分",
 "Divisor":"除数",
 "Document":"单据",
 "Documentation":"单证",
 "Dolphin":"系船柱（码头簇桩）",
 "Domain":"领域",
 "Door":"门（门到门）",
 "Doubt":"疑问",
 "Down":"向下",
 "Draft":"吃水/汇票",
 "Drag":"拖曳",
 "Drain":"排放",
 "Draught":"吃水",
 "Draw":"绘制/开（汇票）",
 "Dredge":"疏浚",
 "Drift":"漂移",
 "Drive":"驱动",
 "Drop":"掉落",
 "Drum":"桶（液体桶）",
 "Dry":"干货/干",
 "Dry bulk":"干散货",
 "Dry cargo":"干货",
 "Due":"到期/应付",
 "Dues":"规费（港口规费）",
 "Dunnage":"垫料（隔垫料）",
 "Duplicate":"副本",
 "Durable":"耐用的",
 "Duty":"关税/义务",
 "Duty paid":"已付税",
 "Dwarf":"矮（非航运）",
 "Dynamic":"动态的",
 # ---- E ----
 "EAN":"欧洲商品编号（EAN条码）",
 "Earned":"赚得",
 "Earnest":"定金",
 "Ease":"缓和",
 "East":"东",
 "Ebb":"落潮",
 "Ecology":"生态",
 "Economic":"经济的",
 "Economy":"经济",
 "Edge":"边缘",
 "Edition":"版次",
 "Effect":"效力",
 "Effective":"有效的",
 "Effort":"努力",
 "Elastic":"弹性的",
 "Electric":"电的",
 "Electronic":"电子的",
 "Element":"要素",
 "Eligible":"合格的",
 "Eliminate":"消除",
 "Emerge":"出现",
 "Emission":"排放",
 "Emphasis":"重点",
 "Empire":"帝国（非航运）",
 "Employ":"雇佣",
 "Empty":"空箱",
 "Empty return":"空箱回运",
 "End":"端部",
 "Endorse":"背书",
 "Endorsement":"背书",
 "Energy":"能源",
 "Engine":"引擎/主机",
 "Engineer":"工程师/轮机员",
 "Enhanced":"增强的",
 "Enquiry":"询盘",
 "Enter":"进入",
 "Enterprise":"企业",
 "Entrepot":"中转港/自由贸易港",
 "Entry":"报关/进入",
 "Equal":"相等",
 "Equipment":"设备（集装箱等设备）",
 "Equity":"权益",
 "Error":"错误",
 "Escape":"逃逸",
 "Especially":"尤其",
 "Estimate":"估计",
 "Euro":"欧元",
 "Evade":"规避",
 "Even":"偶数/平坦",
 "Event":"事件",
 "Evidence":"证据",
 "Exact":"准确的",
 "Examination":"检验",
 "Example":"示例",
 "Exceed":"超过",
 "Except":"除…外",
 "Excess":"超额",
 "Exchange":"交换/兑换",
 "Exclude":"排除",
 "Execute":"执行",
 "Exemption":"豁免",
 "Exercise":"行使",
 "Exhibit":"陈列",
 "Exit":"出口",
 "Expense":"费用",
 "Explicit":"明确的",
 "Export":"出口",
 "Exposure":"风险敞口",
 "Express":"快递/明确",
 "Extend":"延长",
 "Extent":"范围",
 "External":"外部的",
 "Extra":"额外",
 "Extract":"提取",
 # ---- F ----
 "Facility":"设施",
 "Factor":"因素/因数",
 "Fade":"褪色",
 "Failure":"失败",
 "Fair":"公平/晴天",
 "Fall":"落下/秋季",
 "False":"虚假",
 "Famine":"饥荒（非航运）",
 "Fancy":"花式（非航运）",
 "Fare":"运费（客运）/费用",
 "Farm":"农场（非航运）",
 "Fashion":"时尚（非航运）",
 "Fast":"系牢/快",
 "Fat":"肥（非航运）",
 "Fathom":"英寻（水深单位）",
 "Fault":"故障",
 "Favour":"优惠",
 "Feasible":"可行的",
 "Feature":"特征",
 "Fee":"费",
 "Feed":"喂给（喂给支线）",
 "Feeder":"支线船",
 "Feeder service":"支线运输",
 "Fence":"围栏（非航运）",
 "Ferry":"渡轮",
 "Festival":"节日（非航运）",
 "Fever":"发热（非航运）",
 "Fibre":"纤维",
 "Fictitious":"虚构的",
 "Fiddle":"填料（非航运）",
 "Fief":"封地（非航运）",
 "Field":"场/字段",
 "Fierce":"猛烈（非航运）",
 "Figure":"数字/图",
 "File":"文件",
 "Fill":"填充",
 "Film":"薄膜",
 "Filter":"过滤器",
 "Final":"最终",
 "Finance":"融资",
 "Find":"找到",
 "Fine":"罚款/细",
 "Finger":"手指（非航运）",
 "Firm":"商行/稳固",
 "First":"第一",
 "Fish":"鱼（非航运）",
 "Fit":"适配",
 "Flag":"船旗",
 "Flame":"火焰",
 "Flash":"闪（闪点）",
 "Flat":"平/平板（平车）",
 "Fleet":"船队",
 "Flexible":"灵活的",
 "Float":"漂浮/渡驳",
 "Floating":"浮动的",
 "Flood":"涨潮/洪水",
 "Floor":"地板",
 "Flow":"流",
 "Fluctuate":"波动",
 "Fluid":"流体",
 "Flush":"齐平",
 "Fly":"飞（非航运）",
 "Foam":"泡沫",
 "Fold":"折叠",
 "Folk":"人们（非航运）",
 "Follow":"跟随",
 "Food":"食品",
 "Foot":"英尺/脚",
 "Forbidden":"禁止",
 "Force":"力量/不可抗力",
 "Fore":"船首的",
 "Forecastle":"首楼",
 "Foreign":"外国的",
 "Foreman":"工头（装卸工长）",
 "Forest":"森林（非航运）",
 "Forge":"伪造",
 "Form":"格式/表单",
 "Format":"格式",
 "Former":"前者",
 "Forward":"前方/转发",
 "Forwarder":"货运代理",
 "Forwarding":"货运代理（业务）",
 "Found":"成立/找到",
 "Foundation":"基础",
 "Fragile":"易碎",
 "Frame":"肋骨（船体框架）",
 "Free":"自由/免（免费）",
 "Free in":"船方不负担装费（FI）",
 "Free out":"船方不负担卸费（FO）",
 "Freeboard":"干舷",
 "Freeze":"冻结",
 "Freight":"运费/货物",
 "Freight forwarder":"货运代理",
 "Freight prepaid":"运费预付",
 "Freight collect":"运费到付",
 "Frequency":"频率",
 "Fresh":"新鲜/淡水",
 "Friend":"朋友（非航运）",
 "Fringe":"边缘",
 "Frozen":"冷冻",
 "Fruit":"水果（非航运）",
 "Fuel":"燃料",
 "Full":"满（整箱）",
 "Fumigate":"熏蒸",
 "Fund":"基金",
 "Fungible":"可替代的",
 "Furl":"卷起（帆）",
 "Furniture":"家具（非航运）",
 "Further":"进一步",
 "Future":"期货/未来",
 # ---- G ----
 "Gain":"增益",
 "Galley":"厨房（船用）",
 "Gallon":"加仑",
 "Gang":"班组（装卸工班）",
 "Gantry":"岸桥（龙门吊）",
 "Gap":"缺口",
 "Gas":"气体",
 "Gauge":"量规",
 "Gear":"属具/设备",
 "General":"总的",
 "General average":"共同海损",
 "Generic":"通用的",
 "Giant":"巨型（非航运）",
 "Gift":"礼品（非航运）",
 "Girl":"女孩（非航运）",
 "Give":"给予",
 "Gland":"密封压盖",
 "Glass":"玻璃",
 "Global":"全球的",
 "Globe":"地球",
 "Glory":"荣耀（非航运）",
 "Glove":"手套（非航运）",
 "Go down":"下驶",
 "Goal":"目标",
 "Going":"进行中",
 "Goods":"货物",
 "Grab":"抓斗",
 "Grace":"宽限（宽限期）",
 "Grade":"等级",
 "Grading":"分级",
 "Grain":"谷物",
 "Grand":"大（非航运）",
 "Grant":"授予",
 "Graph":"图表",
 "Grasp":"掌握",
 "Grass":"草（非航运）",
 "Grate":"格栅",
 "Gravity":"重力",
 "Great":"大",
 "Green":"绿色",
 "Grid":"网格",
 "Grind":"磨（非航运）",
 "Grip":"抓握",
 "Groin":"防波堤（非航运）",
 "Gross":"毛（毛重/总）",
 "Gross tonnage":"总吨（GT）",
 "Ground":"搁浅/地面",
 "Grounding":"搁浅",
 "Group":"组",
 "Grow":"增长",
 "Guard":"守卫",
 "Guess":"猜测（非航运）",
 "Guest":"客人（非航运）",
 "Guide":"指南",
 "Gulf":"海湾",
 "Gun":"炮（非航运）",
 "Guy":"稳索（张索）",
 # ---- H ----
 "Hatch":"舱口",
 "Hatch cover":"舱盖",
 "Haul":"拖运",
 "Haven":"港（避风港）",
 "Hawser":"大缆（系船缆）",
 "Hazard":"危险",
 "Head":"船首/头",
 "Headrope":"头缆",
 "Health":"健康",
 "Heave":"起锚/起伏",
 "Heavy":"重",
 "Heavy lift":"重件货",
 "Heel":"倾侧",
 "Height":"高度",
 "Helm":"舵",
 "Helmsman":"舵工",
 "Hire":"租金（租船租金）",
 "Holder":"持有人",
 "Hold":"货舱",
 "Holiday":"假日（非航运）",
 "Home":"家/本国",
 "Honour":"兑付（承兑付款）",
 "Hook":"吊钩",
 "Hope":"希望（非航运）",
 "Horn":"角（非航运）",
 "Horse":"马（非航运）",
 "Hose":"软管",
 "Host":"主机/东道",
 "Hotel":"酒店（非航运）",
 "Hour":"小时",
 "House":"仓（仓至仓）",
 "House air waybill":"分运单（HAWB）",
 "House bill of lading":"分提单（HBL）",
 "Household":"家庭（非航运）",
 "Hover":"悬停",
 "Hub":"枢纽港",
 "Hull":"船体",
 "Hundredweight":"英担（重量单位）",
 "Hunger":"饥饿（非航运）",
 "Hurricane":"飓风",
 "Hydrant":"消防栓",
 "Hyper":"超（非航运）",
 # ---- I ----
 "Ice":"冰",
 "Icebreaker":"破冰船",
 "Identity":"身份",
 "Ignition":"点火",
 "Illegal":"非法的",
 "Imaginary":"假设的",
 "Immediate":"立即的",
 "Immobilise":"固定",
 "Impact":"冲击",
 "Impart":"告知",
 "Impediment":"妨碍",
 "Import":"进口",
 "Importer":"进口商",
 "Imposition":"强加",
 "Impound":"扣押",
 "Improper":"不当",
 "Improve":"改善",
 "Impulse":"脉冲",
 "In bond":"保税（在关栈）",
 "In transit":"在途",
 "Inboard":"舱内/向内",
 "Inch":"英寸",
 "Include":"包含",
 "Inclusive":"含",
 "Income":"收入",
 "Incorporated":"股份（公司）",
 "Increase":"增加",
 "Incur":"招致",
 "Index":"指数",
 "Indicate":"指示",
 "Indicator":"指示器",
 "Indorse":"背书（同endorse）",
 "Industry":"行业",
 "Inevitable":"不可避免的",
 "Inquiry":"询盘",
 "Insert":"插入",
 "Inside":"内部",
 "Insolvent":"破产的",
 "Inspect":"检验",
 "Inspection":"检验",
 "Install":"安装",
 "Instant":"即时",
 "Institute":"协会（如协会条款）",
 "Institution":"机构",
 "Instruction":"指示",
 "Instrument":"单证/仪器",
 "Insurance":"保险",
 "Insured":"被保险人",
 "Insurer":"保险人",
 "Intake":"进气/摄入量",
 "Integral":"整体的",
 "Integrate":"整合",
 "Integrity":"完整",
 "Intend":"意图",
 "Interchange":"交换（设备交接）",
 "Interest":"利息/利益",
 "Interface":"接口",
 "Interim":"临时",
 "Interline":"联运（公司间）",
 "Intermediate":"中间的",
 "Internal":"内部的",
 "International":"国际的",
 "Interpret":"解释",
 "Interval":"间隔",
 "Intervene":"干预",
 "Inventory":"库存",
 "Invoice":"发票",
 " Invite":"邀请",
 "Involve":"涉及",
 "Inward":"进港（入港）",
 "Issue":"签发",
 "Item":"项目",
 # ---- J ----
 "Jack":"千斤顶（非航运）",
 "Jacket":"外套（非航运）",
 "Jammed":"卡住",
 "Jettison":"投弃（抛弃货物）",
 "Jetty":"突堤码头",
 "Job":"工作",
 "Join":"加入",
 "Joint":"联合的",
 "Joint rate":"联合费率",
 "Journey":"航程",
 "Jurisdiction":"管辖权",
 "Just":"公正",
 # ---- K ----
 "Keel":"龙骨",
 "Keelage":"入港费（古称）",
 "Keelson":"内龙骨",
 "Knot":"节（航速单位，1节=1海里/时）",
 # ---- L ----
 "Label":"标签",
 "Labour":"人工",
 "Laden":"满载的",
 "Landing":"登陆/卸岸",
 "Lane":"航道/航线",
 "Lash":"绑扎",
 "Lashing":"绑扎（系固）",
 "Latitude":"纬度",
 "Launch":"下水/交通艇",
 "Law":"法律",
 "Lay":"放置",
 "Lay days":"装卸期限（ Laydays）",
 "Lay up":"闲置（停航封存）",
 "Layer":"层",
 "Lead":"铅/领先",
 "Leak":"渗漏",
 "Lean":"倾斜",
 "Lease":"租赁",
 "Leave":"离开",
 "Ledger":"总账",
 "Legal":"法律的",
 "Length":"长度",
 "Less":"较少",
 "Less than container load (LCL)":"拼箱（LCL，不足整箱）",
 "Lessor":"出租人",
 "Letter":"信/字母",
 "Letter of credit (L/C)":"信用证（L/C）",
 "Level":"水平",
 "Lever":"杠杆",
 "Liability":"责任",
 "Lien":"留置权",
 "Lifeboat":"救生艇",
 "Liferaft":"救生筏",
 "Lift":"起吊/起吊量",
 "Lighter":"驳船（港内驳）",
 "Lighterage":"驳运费",
 "Limit":"限制",
 "Line":"航线/公司",
 "Liner":"班轮",
 "Liner terms":"班轮条款",
 "Link":"链接",
 "Liquid":"液体",
 "List":"倾斜/清单",
 "Live":"活/通电",
 "Lloyd's":"劳合社（保险市场）",
 "Load":"装载",
 "Load line":"载重线",
 "Loan":"贷款",
 "Local":"当地的",
 "Locate":"定位",
 "Lodge":"提出（索赔）",
 "Log":"航海日志",
 "Long":"长",
 "Long ton":"长吨（英吨，1016公斤）",
 "Longitude":"经度",
 "Look":"看",
 "Loose":"松散",
 "Loss":"损失",
 "Lost":"丢失",
 "Lot":"批",
 "Low":"低",
 "Lower":"下（下层）",
 "Lump":"块（非航运）",
 "Lump sum":"总额（包干运费）",
 "Lunch":"午餐（非航运）",
 # ---- M ----
 "Machine":"机器",
 "Manifest":"舱单",
 "Manifold":"歧管（多路阀）",
 "Manning":"配员",
 "Manual":"手册/手动",
 "Manufacture":"制造",
 "Maritime":"海事的",
 "Mark":"标记",
 "Market":"市场",
 "Marline":"细绳（捻缝绳）",
 "Mast":"桅杆",
 "Master":"船长/正本",
 "Master air waybill":"主运单（MAWB）",
 "Master bill of lading":"主提单（MBL）",
 "Mate":"大副",
 "Mate's receipt":"大副收据",
 "Material":"材料",
 "Maturity":"到期（汇票到期）",
 "Maximum":"最大",
 "Mean":"平均/意指",
 "Measure":"丈量",
 "Measurement":"尺码（体积）",
 "Mechanical":"机械的",
 "Median":"中位",
 "Medium":"中型",
 "Meet":"会面",
 "Melt":"融化（非航运）",
 "Member":"成员",
 "Memorandum":"备忘录",
 "Merchant":"商人",
 "Message":"报文",
 "Metal":"金属",
 "Meter":"米/表",
 "Method":"方法",
 "Metric":"公制",
 "Metric ton":"公吨（1000公斤）",
 "Micro":"微（非航运）",
 "Mile":"英里",
 "Mileage":"英里数",
 "Minimum":"最小",
 "Ministry":"部（非航运）",
 "Minor":"次要",
 "Miscellaneous":"杂项",
 "Misdelivery":"错误交付",
 "Mix":"混合",
 "Mode":"方式（运输方式）",
 "Model":"模型",
 "Modification":"修改",
 "Module":"模块",
 "Moisture":"湿气",
 "Mole":"防波堤/突堤",
 "Monitor":"监控",
 "Monsoon":"季风",
 "Month":"月",
 "Mooring":"系泊",
 "Moor":"系泊",
 "Mortgage":"抵押",
 "Most":"最",
 "Motion":"运动",
 "Motor":"马达",
 "Motor vessel (M.V.)":"内燃机船（M.V.）",
 "Mould":"模（非航运）",
 "Mount":"安装",
 "Mouse":"鼠标（非航运）",
 "Mouth":"河口",
 "Move":"移动",
 "Movement":"移动/运输动态",
 "Much":"多",
 "Muster":"集合（点名）",
 "Mutual":"相互的",
 # ---- N ----
 "Name":"名称",
 "Narrow":"窄",
 "Nation":"国家",
 "Native":"本国",
 "Natural":"自然的",
 "Naval":"海军的",
 "Navigation":"航行",
 "Navigator":"领航员",
 "Near":"近",
 "Necessary":"必要的",
 "Negligence":"疏忽",
 "Negotiable":"可转让的",
 "Negotiate":"议付（议付汇票）",
 "Net":"净",
 "Net tonnage":"净吨（NT）",
 "Network":"网络",
 "Neutral":"中立（中性包装）",
 "New":"新",
 "Next":"下一个",
 "Night":"夜",
 "No claim":"无索赔",
 "No cure no pay":"无效果无报酬（救助原则）",
 "No<? echo":"",
 "Node":"节点",
 "Noise":"噪音",
 "Nominal":"名义的",
 "Non":"非（无）",
 "Non-conference":"非公会（非班轮公会）",
 "Non-negotiable":"不可转让的",
 "Non-vessel operating common carrier (NVOCC)":"无船承运人（NVOCC）",
 "Normal":"正常的",
 "North":"北",
 "Notable":"显著的",
 "Note":"注释/票据",
 "Notice":"通知",
 "Notional":"名义的",
 "Notify":"通知（通知人）",
 "Notwithstanding":"尽管",
 "Number":"编号",
 # ---- O ----
 "Objective":"目标",
 "Obligation":"义务",
 "Obsolescence":"淘汰",
 "Obstruction":"障碍物",
 "Occasion":"场合",
 "Ocean":"海运/大洋",
 "Ocean bill of lading":"海运提单",
 "Ocean freight":"海运费",
 "Odd":"零星",
 "Odour":"气味",
 "Off":"离开/关",
 "Offer":"发盘（要约）",
 "Office":"办公室",
 "Offset":"抵消",
 "Oil":"油",
 "On board":"已装船",
 "On deck":"甲板上",
 "On hire":"起租",
 "Onward":" onward（后续运输）",
 "Open":"开放/开舱",
 "Open account":"记账（赊账）",
 "Open cover":"预约保险",
 "Open policy":"预约保单",
 "Operation":"操作",
 "Operator":"经营人",
 "Opinion":"意见",
 "Optimum":"最优",
 "Option":"选择权",
 "Oral":"口头的",
 "Order":"指示/订单",
 "Order bill of lading":"指示提单",
 "Ordinary":"普通",
 "Organisation":"组织",
 "Origin":"起运地/原产地",
 "Original":"正本",
 "Other":"其他",
 "Otherwise":"否则",
 "Out":"出",
 "Out of gauge":"超限（超尺寸货）",
 "Out turn":"卸货状况",
 "Outward":"出港",
 "Over":"越过/超过",
 "Overage":"溢装",
 "Overbook":"超订",
 "Overcarry":"错运过站",
 "Overcharge":"多收费",
 "Overland":"陆上",
 "Overload":"超载",
 "Overtime":"加班",
 "Owner":"船东/货主",
 # ---- P ----
 "Package":"包装/件",
 "Packaging":"包装",
 "Packing":"包装",
 "Packing list":"装箱单",
 "Pad":"垫",
 "Paid":"已付",
 "Pail":"提桶",
 "Pallet":"托盘",
 "Palletisation":"托盘化",
 "Panama":"巴拿马（运河/吨）",
 "Par":"平价",
 "Parcel":"包裹/宗",
 "Pardon":"赦免",
 "Parent":"母公司",
 "Parity":"平价",
 "Part":"部分",
 "Particular average":"单独海损",
 "Party":"方（当事人）",
 "Pass":"通过",
 "Passage":"通行/航程",
 "Passenger":"旅客",
 "Paste":"粘贴（非航运）",
 "Patent":"专利",
 "Path":"路径",
 "Pattern":"模式",
 "Payload":"有效载荷",
 "Payment":"付款",
 "Pier":"突堤码头/栈桥",
 "Pilferage":"偷窃（小偷小摸）",
 "Pilot":"引航员",
 "Pilotage":"引航费",
 "Pin":"销",
 "Pinnace":"小艇（非航运）",
 "Pipe":"管",
 "Pit":"坑（非航运）",
 "Pitch":"俯仰/沥青",
 "Place":"地点",
 "Plain":"plain（平/明）",
 "Plan":"计划",
 "Plant":"工厂（非航运）",
 "Plate":"板材",
 "Platform":"平台",
 "Play":"玩（非航运）",
 "Plead":"抗辩",
 "Plug":"插头",
 "Point":"点",
 "Policy":"保单/政策",
 "Pollution":"污染",
 "Pool":"联营（池）",
 "Port":"港口",
 "Port of call":"挂靠港",
 "Port of discharge":"卸货港",
 "Port of loading":"装货港",
 "Position":"位置",
 "Positive":"正面的",
 "Possession":"占有",
 "Post":"邮寄/后",
 "Posture":"姿态",
 "Potable":"饮用（饮用水）",
 "Potential":"潜在",
 "Pound":"磅/镑",
 "Power":"动力",
 "Practice":"惯例",
 "Preamble":"前言",
 "Precaution":"预防",
 "Precedence":"优先",
 "Precious":"贵重",
 "Precise":"精确",
 "Preferential":"优惠",
 "Premium":"保费",
 "Prepaid":"预付",
 "Prepayment":"预付",
 "Presence":"到场",
 "Preservation":"保存",
 "Press":"压",
 "Pressure":"压力",
 "Presume":"推定",
 "Prevail":"通行",
 "Prevent":"防止",
 "Price":"价格",
 "Primary":"首要",
 "Prime":"主要/ prime（优质的）",
 "Principal":"委托人/本金",
 "Priority":"优先",
 "Private":"私人的",
 "Privilege":"特权",
 "Prize":"捕获品（捕获奖）",
 "Probability":"概率",
 "Procedure":"程序",
 "Proceed":"进行",
 "Process":"过程",
 "Procure":"取得",
 "Produce":"生产",
 "Product":"产品",
 "Professional":"专业的",
 "Profit":"利润",
 "Program":"程序",
 "Prohibit":"禁止",
 "Project":"项目",
 "Promise":"承诺",
 "Promote":"促进",
 "Prompt":"即期（即期付款）",
 "Proof":"证明",
 "Proper":"适当",
 "Property":"财产",
 "Proposal":"提议",
 "Protect":"保护",
 "Protest":"海事声明/拒付证书",
 "Protocol":"议定书",
 "Provide":"提供",
 "Provisions":"给养（船用补给）",
 "Proxy":"代理",
 "Public":"公共",
 "Publish":"公布",
 "Pump":"泵",
 "Punitive":"惩罚",
 "Purchase":"购买",
 "Pure":"纯",
 "Purpose":"目的",
 "Push":"推",
 # ---- Q ----
 "Quadrant":"象限（四分仪）",
 "Qualification":"资格",
 "Quality":"质量",
 "Quarantine":"检疫",
 "Quarter":"船尾两舷/四分之一",
 "Quarterdeck":"后甲板",
 "Quay":"码头（顺岸码头）",
 "Query":"查询",
 "Question":"问题",
 "Quick":"快",
 "Quota":"配额",
 "Quote":"报价",
 # ---- R ----
 "Rabbit":"兔（非航运）",
 "Rack":"架",
 "Radar":"雷达",
 "Radiotelegraph":"无线电报",
 "Rail":"铁路/栏杆",
 "Railway":"铁路",
 "Range":"范围/量程",
 "Rank":"等级",
 "Rate":"费率",
 "Rating":"等级/定级",
 "Ratio":"比率",
 "Raw":"原料",
 "Reachable":"可达",
 "React":"反应",
 "Read":"读",
 "Ready":"备妥",
 "Real":"真实",
 "Rebate":"回扣（运费回扣）",
 "Receipt":"收据",
 "Receive":"收到",
 "Receiver":"收货人",
 "Recent":"最近",
 "Reefer":"冷藏箱（冷藏集装箱）",
 "Reefer container":"冷藏集装箱",
 "Refrigerated":"冷藏的",
 "Refund":"退款",
 "Refusal":"拒绝",
 "Refuse":"拒绝",
 "Regard":"关于",
 "Region":"区域",
 "Register":"登记/注册（登记吨）",
 "Registered":"已登记",
 "Regression":"回归",
 "Regulation":"规章",
 "Reimburse":"偿付",
 "Reinsurance":"再保险",
 "Reject":"拒收",
 "Related":"相关",
 "Release":"放行",
 "Relief":"救济",
 "Remainder":"剩余",
 "Remit":"汇付",
 "Remittance":"汇款",
 "Remove":"移除",
 "Renewal":"续保/续展",
 "Rent":"租金",
 "Repack":"重新包装",
 "Repair":"修理",
 "Repeat":"重复",
 "Replace":"替换",
 "Report":"报告",
 "Representative":"代表",
 "Reprint":"重印",
 "Reputation":"声誉",
 "Request":"请求",
 "Require":"要求",
 "Rescue":"救助",
 "Research":"研究",
 "Reserve":"保留/准备金",
 "Residence":"住所（非航运）",
 "Residual":"剩余",
 "Resistance":"阻力",
 "Resolution":"决议",
 "Resource":"资源",
 "Respond":"回应",
 "Responsibility":"责任",
 "Restow":"翻舱（重装）",
 "Restraint":"限制",
 "Restrict":"限制",
 "Result":"结果",
 "Resume":"恢复",
 "Retail":"零售",
 "Retention":"保留",
 "Retroactive":"追溯",
 "Return":"返回",
 "Revaluation":"重估",
 "Revenue":"收入",
 "Reverse":"反向",
 "Revise":"修订",
 "Revocation":"撤销",
 "Reward":"报酬",
 "Rider":"附条（批单）",
 "Rig":"钻机/索具",
 "Right":"右/权利",
 "Rigging":"索具",
 "Ring":"环",
 "Riot":"暴动",
 "Risk":"风险",
 "River":"河",
 "Road":"路（非航运）",
 "Roadstead":"锚地（港外锚地）",
 "Ro-Ro":"滚装（滚装船）",
 "Roll":"滚动",
 "Roller":"滚轮",
 "Roman":"罗马（非航运）",
 "Rope":"绳",
 "Rot":"腐烂",
 "Rough":"粗/恶劣（恶劣天气）",
 "Round":"圆/往返",
 "Route":"航线/路线",
 "Routine":"例行",
 "Royalty":"特许权使用费",
 "Rubber":"橡胶",
 "Rudder":"舵",
 "Rule":"规则",
 "Run":"运行",
 "Runner":"滑车（跑绳）",
 "Runoff":"径流（非航运）",
 "Rural":"乡村（非航运）",
 # ---- S ----
 "Saddle":"鞍（非航运）",
 "Safe":"安全",
 "Safe port":"安全港",
 "Sail":"帆/航行",
 "Sailing":"航行（船期）",
 "Sailing date":"开航日",
 "Sale":"销售",
 "Salvage":"救助（海难救助）/残值",
 "Salvage charges":"救助费",
 "Same":"相同",
 "Sample":"样品",
 "Sanction":"制裁/许可",
 "Sand":"沙",
 "Satellite":"卫星",
 "Saturated":"饱和",
 "Save":"救助（同salvage古义）/节省",
 "Scale":"尺度/比例",
 "Scantling":"船材尺度",
 "Scrap":"废料",
 "Screen":"屏幕（非航运）",
 "Screw":"螺旋桨（暗轮）",
 "Seaworthiness":"适航性",
 "Seaworthy":"适航的",
 "Second":"第二",
 "Secret":"秘密",
 "Section":"段",
 "Secure":"系固/担保",
 "Security":"担保/安全",
 "Sedan":"轿车（非航运）",
 "See":"见",
 "Segment":"段",
 "Segregate":"隔离",
 "Seizure":"扣押（捕获）",
 "Self":"自身",
 "Sell":"出售",
 "Sender":"发货人",
 "Senior":"高级",
 "Sensitive":"敏感",
 "Separate":"分开",
 "Sequence":"顺序",
 "Sergeant":"军士（非航运）",
 "Series":"系列",
 "Service":"服务",
 "Set":"套/设定",
 "Settle":"结清",
 "Settlement":"结算",
 "Several":"若干",
 "Severe":"严重",
 "Sew":"缝（非航运）",
 "Shackle":"卸扣（连接卸扣）",
 "Shaft":"轴（尾轴）",
 "Shake":"震动",
 "Shall":"须",
 "Shape":"形状",
 "Share":"份额",
 "Sharp":"尖/急剧",
 "Shed":"棚（货棚）",
 "Sheer":"舷弧（船舷弧）",
 "Sheet":"张（帆）/表",
 "Shell":"壳（船壳）",
 "Shift":"移泊/换档",
 "Shifting":"移泊",
 "Ship":"船/装运",
 "Ship broker":"船舶经纪人",
 "Ship chandler":"船用物料商",
 "Ship owner":"船东",
 "Ship's bag":"船邮袋",
 "Ship's husband":"船东代表（船舶经理人）",
 "Shipment":"装运/货物",
 "Shipper":"托运人",
 "Shipping":"航运",
 "Shipping advice":"装运通知",

 "Shipping note":"装运通知（托运单）",
 "Shipping order":"装货单（S/O）",
 "Shore":"岸",
 "Short":"短",
 "Short ship":"短装（漏装）",
 "Shortdelivery":"短交（短少交付）",
 "Show":"显示",
 "Shrink":"收缩",
 "Shut":"关闭",
 "Shuttle":"穿梭（穿梭运输）",
 "Sick":"病（非航运）",
 "Side":"侧",
 "Signal":"信号",
 "Silent":"沉默",
 "Similar":"类似",
 "Single":"单一",
 "Sister ship":"姊妹船",
 "Site":"现场",
 "Situation":"情况",
 "Six":"六（非航运）",
 "Size":"尺寸",
 "Skid":"滑撬（衬垫）",
 "Skin":"皮（非航运）",
 "Sling":"吊索（吊货索）",
 "Slip":"滑/泊位（造船台）",
 "Slogan":"标语（非航运）",
 "Slope":"坡度",
 "Slot":"箱位（箱位预订）",
 "Slow":"慢",
 "Small":"小",
 "Smart":"智能（非航运）",
 "Smoke":"烟",
 "Snap":"扣（非航运）",
 "Snow":"雪",
 "Soak":"浸泡（非航运）",
 "Social":"社会的",
 "Society":"船级社/协会",
 "Socket":"插座",
 "Soft":"软",
 "Soil":"土壤（非航运）",
 "Solar":"太阳",
 "Sold":"售出",
 "Sole":"唯一",
 "Solid":"固体",
 "Solution":"解决方案",
 "Solve":"解决",
 "Sort":"分拣",
 "Sound":"完好的/声",
 "Source":"来源",
 "South":"南",
 "Space":"舱位",
 "Spare":"备用",
 "Spark":"火花",
 "Speak":"说（非航运）",
 "Special":"特殊",
 "Specification":"规格",
 "Specify":"指定",
 "Speed":"速度",
 "Spell":"拼写（非航运）",
 "Spend":"花费",
 "Spike":"钉（非航运）",
 "Spill":"溢出",
 "Spin":"旋转（非航运）",
 "Spirit":"精神（非航运）",
 "Splice":"插接（绳缆接合）",
 "Split":"拆分",
 "Spoilage":"损坏",
 "Sponsor":"赞助",
 "Spot":"现货/现场",
 "Spout":"喷口（非航运）",
 "Spread":" spread（展宽）",
 "Spring":"弹簧/缆（倒缆）",
 "Sprinkle":"洒（非航运）",
 "Spur":"支线（非航运）",
 "Square":"平方/方",
 "Stable":"稳定",
 "Stack":"堆垛",
 "Staff":"员工",
 "Stage":"阶段",
 "Stain":"污渍",
 "Stake":"桩（非航运）",
 "Stale":"过期（过期提单）",
 "Stand":"站立/立场",
 "Standard":"标准",
 "Starboard":"右舷",
 "Stated":"所述",
 "Station":"站",
 "Statute":"成文法",
 "Statutory":"法定的",
 "Stay":"稳索/停留",
 "Steady":"稳定",
 "Steal":"偷（非航运）",
 "Steamer":"汽船",
 "Steamship":"汽船（S.S.）",
 "Steel":"钢",
 "Stem":"船首柱",
 "Step":"步骤",
 "Stern":"船尾",
 "Stiff":"硬（稳性大）",
 "Still":"仍然/静止",
 "Stipulate":"规定",
 "Stock":"库存/股票",
 "Stolen":"被盗",
 "Stop":"停止",
 "Storage":"仓储",
 "Store":"储存",
 "Storm":"风暴",
 "Story":"故事（非航运）",
 "Stow":"积载（装载）",
 "Stowage":"积载",
 "Straight":"直（直运）",
 "Strain":"应变",
 "Strand":"搁浅/股（缆股）",
 "Strap":"带",
 "Stream":"流",
 "Street":"街道（非航运）",
 "Stress":"应力",
 "Strict":"严格",
 "Strike":"罢工",
 "String":"绳/串",
 "Strip":"拆箱（掏箱）",
 "Strong":"强",
 "Structure":"结构",
 "Struggle":"挣扎（非航运）",
 "Stud":"双头螺栓（非航运）",
 "Stuff":"装箱（装柜）",
 "Subject":"主题/以…为条件",
 "Submit":"提交",
 "Subrogation":"代位求偿",
 "Subsidise":"补贴",
 "Subsidy":"补贴",
 "Substance":"物质",
 "Substitute":"替代",
 "Succeed":"成功",
 "Such":"如此",
 "Suffer":"遭受",
 "Sugar":"糖（非航运）",
 "Suggest":"建议",
 "Suit":" suits（套/诉讼）",
 "Summary":"摘要",
 "Summer":"夏季（夏季载重线）",
 "Summons":"传票",
 "Sun":"太阳",
 "Super":"超级",
 "Superintendence":"监督",
 "Superior":"上级",
 "Supervise":"监督",
 "Supply":"供应",
 "Support":"支持",
 "Suppose":"假设",
 "Supreme":"最高",
 "Sure":"确定",
 "Surface":"表面",
 "Surcharge":"附加费",
 "Surplus":"盈余",
 "Survey":"检验/鉴定",
 "Surveyor":"检验人/验船师",
 "Suspect":"怀疑",
 "Suspend":"暂停",
 "Sustain":"遭受（损失）",
 "Swamp":"淹没",
 "Swap":"交换",
 "Sway":"摇摆",
 "Sweat":"汗（非航运）",
 "Sweep":"清扫",
 "Sweet":"甜（非航运）",
 "Swift":"快",
 "Swim":"游泳（非航运）",
 "Swing":"摆动/调头（掉头）",
 "Switch":"切换/开关",
 "Symbol":"符号",
 "Sympathy":"同情（非航运）",
 "System":"系统",
 # ---- T ----
 "Table":"表",
 "Tackle":"索具/滑车组",
 "Tare":"皮重",
 "Target":"目标",
 "Tariff":"运价本/关税",
 "Tarnish":"锈蚀",
 "Tender":"供应船/投标",
 "Tenor":"期限（汇票期限）",
 "Tension":"张力",
 "Terminal":"码头/场站",
 "Termination":"终止",
 "Terms":"条款",
 "Territory":"区域",
 "Test":"测试",
 "Three":"三（非航运）",
 "Threshold":"门槛",
 "Throat":"喉（非航运）",
 "Through":"联运/直达",
 "Through bill of lading":"联运提单",
 "Through rate":"联运费率",
 "Tidal":"潮汐的",
 "Tide":"潮汐",
 "Tier":"层（箱层）",
 "Tight":"紧密",
 "Time":"时间",
 "Time charter":"期租（定期租船）",
 "Title":"所有权/标题",
 "Tolerance":"公差",
 "Toll":"通行费",
 "Ton":"吨",
 "Tonnage":"吨位",
 "Tool":"工具",
 "Top":"顶",
 "Topic":"主题",
 "Tornado":"龙卷风",
 "Torrent":"急流（非航运）",
 "Tow":"拖带",
 "Towage":"拖带费",
 "Tower":"塔",
 "Trade":"贸易/航线",
 "Trader":"贸易商",
 "Traffic":"交通/运量",
 "Trailer":"拖车",
 "Train":"火车/列车",
 "Tramp":"不定期船",
 "Tranship":"转运",
 "Transhipment":"转运",
 "Transit":"过境/在途",
 "Transload":"换装",
 "Transmit":"传输",
 "Transport":"运输",
 "Transportation":"运输",
 "Transship":"转运",
 "Transshipment":"转运",
 "Trap":"陷阱（非航运）",
 "Travel":"旅行（非航运）",
 "Treaty":"条约",
 "Trend":"趋势",
 "Trial":"试（试航）",
 "Trim":"平舱/纵倾",
 "Trip":"航次",
 "Tropic":"回归线（热带载重线）",
 "Trouble":"麻烦",
 "Trough":"波谷",
 "Truck":"卡车",
 "True":"真（真北/真实）",
 "Trust":"信托",
 "Tube":"管",
 "Tug":"拖船",
 "Tugboat":"拖船",
 "Tumble":"翻倒（非航运）",
 "Turbine":"汽轮机",
 "Turn":"转/轮次",
 "Turnaround":"周转（船舶周转）",
 "Tween deck":"二层甲板",
 "Twist":"扭",
 "Twistlock":"扭锁（集装箱锁）",
 "Type":"类型",
 # ---- U ----
 "Ullage":"空档（液体舱空余）",
 "Ultimate":"最终",
 "Unclaimed":"无人认领",
 "Unclarified":"未澄清",
 "Unclean":"不清洁（不清洁提单）",
 "Uncommitted":"未承诺",
 "Unconfirmed":"不保兑（不保兑信用证）",
 "Undelivered":"未交付",
 "Undercharge":"少收费",
 "Underdeck":"甲板下",
 "Underlie":"构成基础",
 "Underwriter":"保险人（承保人）",
 "Underwriting":"承保",
 "Undischarged":"未卸",
 "Unfair":"不公平",
 "Uniform":"统一",
 "Union":"工会/联合",
 "Unique":"独特",
 "Unit":"单位/单元",
 "Unit load":"单元化装载",
 "Unitary":"单一",
 "United":"联合",
 "Unlawful":"非法",
 "Unlimited":"无限",
 "Unload":"卸货",
 "Unpacked":"未包装",
 "Unpaid":"未付",
 "Unsafe":"不安全",
 "Unseasonal":"不合时令",
 "Unstable":"不稳定",
 "Untie":"解缆",
 "Unused":"未使用",
 "Unworthy":"不值得",
 "Upbound":"上行",
 "Update":"更新",
 "Upgrade":"升级",
 "Uphold":"维护",
 "Uplift":"提升（提取）",
 "Upper":"上部",
 "Upstream":"上游",
 "Urgent":"紧急",
 "Use":"使用",
 "Useful":"有用",
 "Usual":"通常",
 "Usurp":"篡夺（非航运）",
 "Utilise":"利用",
 "Utility":"公用事业",
 # ---- V ----
 "Vacancy":"空缺",
 "Valid":"有效",
 "Valuable":"贵重",
 "Value":"价值",
 "Valuation":"估价",
 "Van":"厢式车（非航运）",
 "Variance":"差异",
 "Variant":"变体",
 "Variation":"变化/磁差",
 "Vehicle":"车辆",
 "Velocity":"速度",
 "Vent":"通风口",
 "Ventilate":"通风",
 "Ventilation":"通风",
 "Verb":"动词（非航运）",
 "Verify":"核实",
 "Version":"版本",
 "Vessel":"船舶",
 "Vessel sharing agreement (VSA)":"舱位共享协议（VSA）",
 "Veto":"否决（非航运）",
 "Via":"经由",
 "Vibe":"振动（非航运）",
 "Vice":"副（非航运）",
 "View":"视图",
 "Vigilance":"警戒",
 "Vintage":"年份（非航运）",
 "Violation":"违反",
 "Violence":"暴力",
 "Virtual":"虚拟",
 "Visible":"可见",
 "Volume":"体积/量",
 "Voluntary":"自愿",
 "Voyage":"航次",
 "Voyage charter":"航次租船",
 "Vulnerable":"脆弱",
 # ---- W ----
 "Wages":"工资",
 "Waive":"放弃（弃权）",
 "Waiver":"弃权（免责条款）",
 "Walk":"走（非航运）",
 "Wall":"墙",
 "Wanted":"招聘（非航运）",
 "Warehouse":"仓库",
 "Warehousing":"仓储",
 "Warrant":"仓单/授权",
 "Warranty":"保证（质量保证）",
 "Wash":"冲洗",
 "Waste":"废料",
 "Watch":"班（值班）",
 "Water":"水",
 "Waterline":"水线",
 "Waterway":"水道",
 "Way":"路/方式",
 "Waybill":"运单",
 "Weak":"弱",
 "Wear":"磨损",
 "Weather":"天气",
 "Weather routeing":"气象导航",
 "Web":"网",
 "Weekly":"每周",
 "Weight":"重量",
 "Weight ton":"重量吨",
 "Welch":"逃避（非航运）",
 "Welding":"焊接",
 "Well":"井（锚链孔/货井）",
 "West":"西",
 "Wet":"湿",
 "Wharf":"码头",
 "Wheel":"舵轮",
 "Whelp":"绞盘（非航运）",
 "Wide":"宽",
 "Width":"宽度",
 "Wife":"妻子（非航运）",
 "Wild":"野生（非航运）",
 "Will":"将",
 "Wind":"风",
 "Window":"窗口（非航运）",
 "Windward":"上风",
 "Wing":"翼（舷侧）",
 "Winter":"冬季（冬季载重线）",
 "Wire":"钢丝（钢丝绳）",
 "Withdraw":"撤回",
 "Withstand":"承受",
 "Witness":"见证",
 "Wood":"木材",
 "Word":"词",
 "Work":"工作",
 "Working":"工作/营运",
 "Works":"工程",
 "World":"世界",
 "Worm":"蠕虫（非航运）",
 "Worst":"最差",
 "Worth":"价值",
 "Would":"将",
 "Wound":"伤口（非航运）",
 "Wrap":"包装",
 "Wreck":"沉船/残骸",
 "Wring":"绞（非航运）",
 "Write":"写",
 "Wrong":"错误",
 # ---- X ----
 "X-ray":"X光（非航运）",
 "X-ray inspection":"X光查验",
 "X-region":"X区（非航运）",
 "Xenon":"氙（非航运）",
 "Xerox":"复印（非航运）",
 "Xylophone":"木琴（非航运）",
 "X-axis":"X轴（非航运）",
 "X-band":"X波段（雷达）",
 # ---- Y ----
 "Yard":"堆场/船厂",
 "Yard tractor":"堆场拖车",
 "Yaw":"偏航",
 "Year":"年",
 "Yellow":"黄色",
 "Yield":"收益/产出",
 "Yoke":"轭（舵轭）",
 "Young":"年轻（非航运）",
 # ---- Z ----
 "Zeal":"热忱（非航运）",
 "Zero":"零",
 "Zinc":"锌",
 "Zone":"区域/区（如 timezone 时区）",
}

out = []
out.append("# 航运术语表 · 中英对照（A–Z）")
out.append("")
out.append("> 来源：Maersk 航运术语表（https://www.maersk.com.cn/support/glossaries/shipping-terms），共 %d 条术语。" % len(terms))
out.append("> 英文释义为马士基官网原文；中文译名为整理翻译，供「航运派」建站内容参考。")
out.append("")
out.append("| 字母 | 英文术语 | 中文译名 | 英文释义 |")
out.append("| --- | --- | --- | --- |")
import re as _re
# 合并补充中文译名
try:
    _extra = json.load(open('zh_extra.json', encoding='utf-8'))
    zh.update(_extra)
except Exception as e:
    print('zh_extra load warn:', e)
missing=[]
for i,(name,desc) in enumerate(terms,1):
    name = html.unescape(name)
    name = _re.sub(r'\s+',' ',name).strip()
    name = name.replace('( ','(').replace(' )',')')
    z = zh.get(name, "")
    if not z:
        missing.append(name)
    if not z:
        z = "（待补译）"
    desc = desc.replace("|","/").replace("\n"," ")
    if len(desc) > 240:
        desc = desc[:240] + "…"
    out.append("| %s | %s | %s | %s |" % (name[:1].upper(), name, z, desc))

open('航运术语表-中英对照.md','w',encoding='utf-8').write("\n".join(out))
print("written 航运术语表-中英对照.md with", len(terms), "rows")
# report how many missing
print("missing zh count (normalized):", len(missing))
print("sample missing:", missing[:15])
